* Periods in the Use of Euler-Type Diagrams
Jens Lemanski (June 2017)

A neat paper that identifies and divides the usage of Euler-type diagrams (line as well as circle diagrams) in the 16th – 18th century.

First expansive period from Vives (1531) to Alsted (1614)
The second period began around 1660 with Weigel and ended in 1712 with Lange
Third period of expansion began with 1760 with works of Ploucquet, Euler and Lambert

Euler type diagrams became popular in the debate about intuition which took place in the 1790s between Leibnizians and Kantians.

Similar to an economic cycle, one can speak of ‘periods of expansion and recession’ in the history of Euler-type diagrams.

** Period I (1531 – 1614)

*** Juan Luis Vives (De censura veri et falsi)
*** Nicolaus Reimers (Ursus Dithmarsius)
**** Metamorphosis Logicae

*** Bartholomäus Keckermann
**** Systema Logicæ: Sompendiosa methodo
**** Systema Logicæ: Tribus Libris Adornatvm

*** Alsted

** Period II (1660 – 1712)

*** First School
**** Erhard Weigel in Jena
**** Johann Christoph Sturm
**** Gottfried Wilhelm Leibniz

*** Second School
**** Christian Weise in Zittau
**** Samuel Grosser
**** Johann Christian Lange
***** Nucleus Logicae Weisianae
700 page commentary on the Weise’s handbook of logic. These comments contain numerous diagrams.

Author thinks that Lange’s commentary is the most valuable guide to the development of logic diagrams in the time before Euler.

** Period III (1760 – 1880)

*** Ploucquet
**** Fundamenta Philosophiae Speculativae (1759)

Used squares for logic diagrams

*** Lambert
Neues Organon oder Gedanken über die Erforschung und Bezeichnung des Wahren und dessen Unterscheidung vom Irrtum und Schein (1764)

*** Johann Jakob Brucker

*** Gottlob Benjamin Jäsche
Produced a compilation of logic lectures of Kant including the logical diagrams used

*** Johann August Heinrich Ulrich

*** Gotthelf Samuel Steinbart
Used linear diagrams

*** Johann Gebhardt Ehrenreich Maaß
Used triangles in his logic based on Lambert’s line diagrams

*** Johann Gottfried Kiesewetter
Used circle diagrams to illustrate rules of conversion

*** Georg Samuel Albert Mellin
Linked Kant’s The False Subtlety of the Four Syllogistic Figures with Euler’s and Lambert’s logic.

* Logical Diagrams in the Weigel and Weise Circles

John Venn’s terminology of analytical / logical diagrams seem to have some criteria to classify a diagram as a logical diagram.
Eikosograms

In Symbolic Logic by John Venn, there’s a historical note on the different analytical diagrams employed by personalities from 16th century to 18th century.

Weise:
Two Students — Samuel Grosser and Johann Christian Lange
Weigel:
Johann Christoph Strumm and Gottfried Wilhelm Leibniz

The knowledge of 18th and 19th century literature concerning analytical diagrams between the 1660s and 1710s is said to be restricted to some facts about the book Nucleus Logicae Weisiane from the Weise circle.

It is said that for 19th and 20th century logicians, the book Nucleus Logicae Weisiane was not available, except for may be Hamilton.

Maaß, Fries, Schopenhauer, Bachmann, Bolzano and many others within that period only claimed that analytical diagrams were first used by Euler, Lambert, and Ploucquet.

It is said that Drobisch managed to establish the idea that Nucleus Logicae Weisiane could be a source of logical diagrams prior to the use of Euler, Lambert, and Ploucquet as Lambert has mentioned this book in his notes.

Lambert as the first loose connection between Weise and Weigel circles.

The Additamenta added by Lange to Weise’s Nucleus Logicae is about 700 pages.

It is also supplemented by Inventvm Novvm Quadrati Logic Vniversalis. Both the Additament and Inventvm are full of illustrations.

Lange’s text has tree, triangle, trident, square, cube, bow, wheel, and circle diagrams with various functions.

Lange illustrates regular syllogisms with their terms and judgments and also ethymemes and sorties.

Lange details about his cvbi logici

* Samuel Grosser
** Pharus Intellectus, sive Logica electiva
** Gründliche  Anweisung zur Logica

Both these books have triangle diagrams which were used in a similar fashion by Lange in his ‘Additamenta’

Correspondence was located by Grosser as the central concept by which demonstrations can be made. He used a Gleichnüß (Translated roughly as parable or analogy) to describe the relationship between geometrical figures and conceptual content and the Loci Topici (Locus of the Topic?)

He uses the example of meeting of extremes of a line by drawing circles from the extremes and showing that they meet at a certain point

He also shows that two sides of the the triangle formed inside two circles can be thought of as extension of the subject (BC) and predicate of a judgement (AB).
Q. What is AB?

The dichotomic and polytonic tradition as depending on Ramus and Comenius.

Weies and Leibniz had the same teacher Jacob Thomasius who taught Aristotelian philosophy and especially logic.

It is interesting to see Weigel’s observations in Philosophia Mathematica (166) about how Aristotle used geometrical terms such as boundaries and schemes to describe his logic. Also, it is pretty interesting to note how how describes the use of coincidence and dis-coincidence of boundaries for logical deduction. Particularly interesting is how he says the coincidence or dis-coincidence of the extreme terms (possibly the premise and the conclusion) themselves indicate either true or false conclusion.

The article draws to a close by saying that in the period between 1660 — 1710, the development and circulation of logic diagram begins with Weigel and culminate in the work of Lange.

Also, it is said that logic diagrams in general, but also spatial logic diagrams, go back to ancient sciences.

Weigel had confidence that ancients introduced logic diagrams in accordance with Euclid’s second fifth book of the Elements.
